### PR TITLE
feat(alias): wire AbortSignal cancellation into waitForEvent (fixes #1714)

### LINKED ISSUE #1714: feat(alias): wire AbortSignal cancellation into waitForEvent
## Context

PR #1709 added `waitForEvent(filter, opts?)` to `AliasContext`. The adversarial review identified that the originally-documented `signal?: AbortSignal` field was never wired — no callsite passed a signal, making blocked `waitForEvent` calls unkillable.

Per reviewer guidance, the signal field was removed in the repair commit (option a: ship the minimum, file a follow-up for cancellation).

## What needs to happen

1. Add `signal?: AbortSignal` back to `AliasContext`
2. Create an `AbortController` per alias invocation in each callsite:
   - `packages/command/src/alias-runner.ts` (CLI runner)
   - `packages/daemon/src/alias-executor.ts` (daemon executor)
   - `packages/command/src/commands/phase.ts` (phase execution, both dry-run and real)
3. Wire abort on: SIGINT, process shutdown, daemon orchestrator cancel
4. Pass the signal into `createWaitForEvent(signal)` at each callsite
5. Remove the abort listener in `cleanup()` on normal resolution (the original Should #6 from the review)
6. Add tests verifying:
   - Signal fires → in-progress `waitForEvent` rejects with `AbortError`
   - Pre-aborted signal → immediate rejection
   - Listener cleanup on normal resolution (no leaked listeners)

## References

- PR #1709 adversarial review: Blocker 1
- Issue #1584 (parent feature)

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### PR DESCRIPTION
**Pull request by theshadow27**
## Summary

- **`createWaitForEvent`** now accepts an optional `{ openStream?, signal? }` opts object. Pre-aborted signals reject immediately; in-flight waits reject with a `DOMException` with name `"AbortError"` on fire; abort listener removed from signal on any resolution path — no leaked listeners.
- **`AliasContext`** gains `signal: AbortSignal` (required) — wired to `waitForEvent` automatically, also available for alias authors doing long-running work.
- **`alias-runner.ts`**: creates `AbortController` per invocation, `SIGINT`/`SIGTERM` → abort via per-signal wrappers, listener removed in `finally`.
- **`alias-executor.ts`** (daemon subprocess): wires both `SIGINT` and `SIGTERM` → abort via per-signal wrappers, listener removed in `finally`.
- **`phase.ts`**: wires `SIGINT`/`SIGTERM` → abort in both the dry-run (`runPhase`) and real-execution (`executePhase`) paths.

## Test plan

- [x] `createWaitForEvent` — pre-aborted signal → immediate `AbortError` rejection
- [x] `createWaitForEvent` — signal fires while waiting → `AbortError` rejection
- [x] `createWaitForEvent` — abort listener removed on normal resolution (mock signal, verify listener array is empty)
- [x] `createWaitForEvent` — abort listener removed on timeout (mock signal, verify listener array is empty)
- [x] All 5918 existing tests pass (`bun test`)
- [x] `bun typecheck` and `bun lint` clean

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by theshadow27** [comment]
## Adversarial Review (Delta)

### Changes Since Last Review

| # | Previous Issue | Status | Notes |
|---|----------------|--------|-------|
| 1 | 🔴 SIGINT handler suppresses default termination — regression for non-waitForEvent aliases | ✅ Fixed in 20c33fee | Handler now re-raises the signal after aborting (`process.kill(process.pid, sig)`) so processes without `waitForEvent` still die promptly on Ctrl-C |
| 2 | 🔴 SIGTERM not wired in `alias-runner.ts` or either `phase.ts` path | ✅ Fixed in 20c33fee | Both `runPhase` and `executePhase` now wire SIGTERM alongside SIGINT; `alias-executor.ts` gains re-raise for its existing SIGTERM wire |
| 3 | 🟡 Polymorphic `(openStreamOrSignal?, signalArg?)` signature | ✅ Fixed in 20c33fee | Replaced with `createWaitForEvent({ openStream?, signal? })` options object; all 9 call sites updated (production + tests) |
| 4 | 🟡 `AliasContext.signal` optional but all callsites set it | ✅ Fixed in 20c33fee | `signal` is now required; `alias-bundle.spec.ts` and `alias-dry-run.spec.ts` stubs updated |
| 5 | 🟡 `{ once: true }` + explicit `removeEventListener` — pick one | ✅ Fixed in 20c33fee | Dropped `{ once: true }`; cleanup relies solely on explicit `removeEventListener` |
| 6 | 🟡 Test gaps: abort-after-resolve and concurrent abort+match not covered | ✅ Fixed in 20c33fee | Added `abort after resolve` and `abort after timeout` regression tests verifying the `settled` flag prevents a second rejection |
| 7 | 🟡 `signal.reason` ignored — hardcoded DOMException loses abort cause | ✅ Fixed in 20c33fee | Both the pre-aborted fast path and `onAbort` now use `signal.reason ?? new DOMException(...)` |

### New Issues
No new issues introduced.

### Verdict
✅ **Approve** — all 7 findings resolved. Signal wiring is correct across all three callsites, the API is clean, tests cover the key invariants.

**Comment by theshadow27** [comment]
## QA Verification

**PR:** #1758 — feat(alias): wire AbortSignal cancellation into waitForEvent (fixes #1714)
**Linked issue:** #1714

### Implementation Evidence
- `packages/core/src/alias.ts:157` — `AliasContext.signal: AbortSignal` added (required)
- `packages/core/src/event-filter.ts:120-200` — `createWaitForEvent({ openStream?, signal? })` options-object API; pre-abort fast path; `onAbort` listener wired + cleaned up on every resolution path
- `packages/command/src/alias-runner.ts:28-91` — `AbortController` per invocation, SIGINT+SIGTERM → abort, re-raise after abort, removed in `finally`
- `packages/daemon/src/alias-executor.ts:139-183` — same SIGINT+SIGTERM pattern in the daemon subprocess
- `packages/command/src/commands/phase.ts:821-862, 1133-1187` — both `runPhase` and `executePhase` wired with separate controllers + `finally` cleanup

### Test Coverage
- `packages/core/src/event-filter.spec.ts` — 6 new AbortSignal tests: pre-aborted immediate rejection, fires-while-waiting rejection, listener cleanup on resolve, listener cleanup on timeout, abort-after-resolve settled-flag guard, abort-after-timeout settled-flag guard
- `packages/core/src/alias-bundle.spec.ts` — 7 AliasContext stubs updated with `signal: new AbortController().signal`
- `packages/core/src/alias-dry-run.spec.ts` — 2 AliasContext stubs updated

### Test Results
Not run locally (branch not checked out). CI coverage job ran all tests — tests appear to pass; CI fails at the coverage threshold step, not at individual test failures.

### CI Status
❌ **FAILING** — run [24910253273](https://github.com/theshadow27/mcp-cli/actions/runs/24910253273)

- **`check` job** (21s): `bun run typecheck` exits 1
  ```
  packages/core/src/event-filter.spec.ts(230,40): error TS2559:
  Type '() => { events: AsyncIterable<MonitorEvent>; abort: () => void; }'
  has no properties in common with type '{ openStream?: ...; signal?: AbortSignal | undefined; } | undefined'
  ```
  The repair commit updated all 9 `createWaitForEvent` call sites to the new options-object API, but TypeScript still flags line 230. The repairer must reproduce this locally (`bun run typecheck`) and fix the specific expression TypeScript is rejecting.

- **`coverage` job**: exits 1 at coverage threshold step. Root cause unclear from logs (tests appear to pass individually); may be a branch coverage drop introduced by the new uncovered code paths.

### Step 5b Gate — Unreplied Copilot Threads: **2 BLOCKING**

| Thread ID | File:Line | Finding |
|-----------|-----------|---------|
| 3140070560 | `packages/core/src/event-filter.ts:133` | **Race condition**: `signal` can abort after the `signal?.aborted` check (pre-abort fast path) but before `signal?.addEventListener("abort", onAbort)` is registered inside the Promise constructor. If this window fires, the abort is silently missed and the promise hangs until the stream ends or times out. |
| 3140070599 | `packages/core/src/alias.ts:166` | **Docstring mismatch**: JSDoc says rejection is `DOMException("AbortError")` but the implementation calls `new DOMException("The operation was aborted", "AbortError")` (the first arg is the message, not the name; the name is "AbortError"). The description is technically correct but the quoted form is misleading. |

Per Step 5b arithmetic: `UNREPLIED_COUNT = 2 > 0` → `qa:pass` is not permitted.

### Remaining Work (non-blocking)
None flagged in the issue.

### Outcome
**qa:fail** — Two blockers:
1. `bun run typecheck` exits 1 (TS2559 in `event-filter.spec.ts:230`)
2. Coverage thresholds failing
3. 2 unreplied Copilot inline threads (race condition + docstring) must be replied to or fixed before `qa:pass` can be issued

Action for implementation:
- Run `bun run typecheck` locally on the branch and fix the TS2559 error in `event-filter.spec.ts`
- Investigate and fix the coverage threshold failure (`bun test --coverage` + `bun scripts/check-coverage.ts`)
- Reply to both Copilot threads (fix the race, or dismiss with rationale + follow-up issue ref)

File: packages/core/src/event-filter.ts [hunk 1]
```diff
@@ -117,14 +124,20 @@ type OpenStreamFn = typeof openEventStream;
...
+  openStreamOrSignal?: OpenStreamFn | AbortSignal,
+  signalArg?: AbortSignal,
 ): (filter: EventFilterSpec, opts?: { timeoutMs?: number; since?: number }) => Promise<MonitorEvent> {
+  const openStream: OpenStreamFn = typeof openStreamOrSignal === "function" ? openStreamOrSignal : openEventStream;
+  const signal: AbortSignal | undefined = typeof openStreamOrSignal === "function" ? signalArg : openStreamOrSignal;
+
   return (filter, opts) => {
+    if (signal?.aborted) {
+      return Promise.reject(new DOMException("The operation was aborted", "AbortError"));
+    }
```
[the remark this answers is not in the document]
Comment (theshadow27) [reply packages/core/src/event-filter.ts]: Fixed in a436717c. Restructured to register the abort listener **before** checking `signal.aborted`:

1. `signal?.addEventListener("abort", onAbort)` — registers first
2. `if (signal?.aborted)` — catches pre-aborted signals and any that fired between construction and step 1

The `settle()` guard is idempotent, so if both the listener and the check fire, only the first takes effect. Added a regression test (`"signal aborted between listener registration and check"`) that uses a mock signal whose `aborted` getter flips to `true` inside `addEventListener`, exercising the exact race.

File: packages/core/src/alias.ts [hunk 2]
```diff
@@ -147,16 +147,23 @@ export interface AliasContext {
...
-   * stream ends or errors before a matching event is observed. The
-   * underlying event stream subscription is always cleaned up on
-   * resolve/reject — no leaked subscribers.
-   *
-   * Cancellation via AbortSignal is not yet supported — see #1714.
+   * `opts.timeoutMs` elapses, or with a `DOMException("AbortError")` if
+   * `ctx.signal` fires, or with an `Error` if the underlying event stream
+   * ends or errors before a matching event is observed. The underlying event
+   * stream subscription is always cleaned up on resolve/reject — no leaked
+   * subscribers.
```
[the remark this answers is not in the document]
Comment (theshadow27) [reply packages/core/src/alias.ts]: Fixed in a436717c. Updated the JSDoc to read:

> or with a \`DOMException\` with name \`\"AbortError\"\` if \`ctx.signal\` fires

This matches the actual rejection shape: \`new DOMException(\"The operation was aborted\", \"AbortError\")\`.

**Comment by theshadow27** [comment]
## Repair: a436717c

Fixes all four QA findings:

### 1. AbortSignal race condition (event-filter.ts)
Restructured `createWaitForEvent` to register the abort listener **before** checking `signal.aborted`. The old order (check → register) left a window where a signal firing between the two was silently missed, hanging the promise until timeout/stream end. Post-registration check now catches pre-aborted signals. `settle()` idempotency prevents double-rejection if both paths fire.

### 2. Race regression test (event-filter.spec.ts)
Added `"signal aborted between listener registration and check"` — uses a mock signal whose `aborted` getter flips to `true` inside `addEventListener`, exercising the exact race window.

### 3. TS lint / format fixes (event-filter.spec.ts)
- Replaced `signal!` non-null assertion with `signal?` optional chain
- Isolated mutable state for the race mock into a getter + local variable (avoids TS2352 cast error)
- Fixed yield-less generator in timeout test (`hanging()` now yields a noise event)
- Applied biome formatting

### 4. JSDoc mismatch (alias.ts:166)
Updated docstring from `DOMException("AbortError")` to `DOMException with name "AbortError"` matching the actual `new DOMException("The operation was aborted", "AbortError")` rejection.

All pre-commit checks pass: typecheck, lint, 3951 tests, coverage (91.55% fn / 93.85% lines).

**Comment by theshadow27** [comment]
## QA Verification

**PR:** #1758 — feat(alias): wire AbortSignal cancellation into waitForEvent (fixes #1714)
**Linked issue:** #1714

### Implementation Evidence
- `packages/core/src/alias.ts:157` — `AliasContext.signal: AbortSignal` (required, correctly documented)
- `packages/core/src/event-filter.ts:124-203` — `createWaitForEvent({ openStream?, signal? })` opts-object API; register listener before aborted check to close race; `onAbort`/`cleanup`/`settle` pattern eliminates listener leaks on every resolution path
- `packages/command/src/alias-runner.ts:28-91` — `AbortController` per invocation; SIGINT+SIGTERM → abort then re-raise; removed in `finally`
- `packages/daemon/src/alias-executor.ts:139-183` — identical SIGINT+SIGTERM pattern in daemon subprocess
- `packages/command/src/commands/phase.ts:821-870` (dry-run) and `:1133-1190` (real exec) — identical pattern in both phase execution paths

### Test Coverage
- `packages/core/src/event-filter.spec.ts` — 8 AbortSignal-specific tests: pre-aborted, mid-wait abort, listener cleanup on resolve, listener cleanup on timeout, TOCTOU race (aborted during addEventListener), abort-after-resolve idempotency, abort-after-timeout idempotency
- `packages/core/src/alias-bundle.spec.ts` — 7 existing `AliasContext` stubs updated with `signal: new AbortController().signal`
- `packages/core/src/alias-dry-run.spec.ts` — stubs updated similarly

### Test Results (local)
5921 pass, 0 fail — full suite green.

Local `bun typecheck` (both incremental and `--clean --force` rebuild): **no errors**.

### CI Status
❌ **FAILING** — https://github.com/theshadow27/mcp-cli/actions/runs/24911227880

- `check` job: TypeScript error in CI (not reproducible locally)
  ```
  packages/core/src/event-filter.spec.ts(230,40): error TS2559:
  Type '() => { events: AsyncIterable<MonitorEvent>; abort: () => void; }'
  has no properties in common with type '{ openStream?: ...; signal?: AbortSignal }'
  ```
  Local clean rebuild passes; CI starts fresh with no tsbuildinfo. Needs investigation.

- `coverage` job: Bun crash mid-run (output truncated at `resolveRealpath > returns rea`, exit code 1 — likely Bun SIGSEGV variant that doesn't trigger the 132/139 retry path). May be a pre-existing flaky Bun crash.

### Copilot Inline Threads — HARD BLOCK

**6 unreplied Copilot inline threads** prevent `qa:pass`:

| ID | File | Line | Finding |
|----|------|------|---------|
| 3140235403 | `alias-runner.ts` | 37 | `process.once("SIGINT"/"SIGTERM")` handlers receive NO args in Node/Bun; `sig` is `undefined` → `process.kill(process.pid, undefined)` misbehaves |
| 3140235428 | `phase.ts` | 832 | Same — dry-run path `onSignal(sig)` with undefined `sig` |
| 3140235444 | `phase.ts` | 1144 | Same — real execution path |
| 3140235465 | `alias-executor.ts` | 150 | Same — daemon subprocess |
| 3140235482 | `event-filter.ts` | 129 | PR description says "first arg (polymorphic)" but implementation uses opts object (stale) |
| 3140235498 | `alias.ts` | 157 | PR description says `signal?` optional but interface has `signal` required (stale) |

Threads 1–4 describe a real correctness bug: `process.once("SIGINT", handler)` in Node.js/Bun calls `handler()` with **no arguments** — the signal name is not passed. Fix: capture the signal at registration time:
```typescript
process.once("SIGINT", () => onSignal("SIGINT"));
process.once("SIGTERM", () => onSignal("SIGTERM"));
```
Threads 5–6 are stale PR-description nits — reply to dismiss or update the description.

### Outcome
**qa:fail** — Blocked by:
1. 6 unreplied Copilot inline threads (arithmetic gate — must be 0 before `qa:pass`)
2. CI `check` red: TypeScript error in event-filter.spec.ts on CI (not reproducible locally — needs investigation or a forced clean CI rebuild to confirm)
3. CI `coverage` red: Bun crash exit 1 (may be pre-existing, but blocks merge)

Action for implementation:
- Fix the `sig` undefined bug in all four callsites (threads 1–4)
- Reply to threads 5–6 dismissing or updating PR description
- Re-push and confirm CI goes green

File: packages/command/src/alias-runner.ts [hunk 3]
```diff
@@ -28,48 +28,64 @@ import {
...
 
 export async function runAlias(aliasPath: string, cliArgs: Record<string, string>, jsonInput?: string): Promise<void> {
-  const mcpProxy = createMcpProxy({ cwd: () => process.cwd() });
+  const controller = new AbortController();
+  const onSignal = (sig: string) => {
+    controller.abort();
+    process.off("SIGINT", onSignal);
+    process.off("SIGTERM", onSignal);
+    process.kill(process.pid, sig);
+  };
```
[the remark this answers is not in the document]
Comment (theshadow27) [reply packages/command/src/alias-runner.ts]: Fixed in 7b4b1130. Replaced the single `onSignal(sig: string)` handler with per-signal wrappers that capture the signal name via closure:

```typescript
const onSignal = (sig: NodeJS.Signals) => {
  controller.abort();
  process.off("SIGINT", onInt);
  process.off("SIGTERM", onTerm);
  process.kill(process.pid, sig);
};
const onInt = () => onSignal("SIGINT");
const onTerm = () => onSignal("SIGTERM");
```

Same pattern applied to all 4 callsites (alias-runner.ts, alias-executor.ts, phase.ts ×2).

File: packages/command/src/commands/phase.ts [hunk 4]
```diff
@@ -821,6 +821,16 @@ async function runPhase(argv: string[], d: PhaseInstallDeps): Promise<void> {
...
 
+  const controller = new AbortController();
+  const onSignal = (sig: string) => {
+    controller.abort();
+    process.off("SIGINT", onSignal);
+    process.off("SIGTERM", onSignal);
+    process.kill(process.pid, sig);
+  };
+  process.once("SIGINT", onSignal);
+  process.once("SIGTERM", onSignal);
```
[the remark this answers is not in the document]
Comment (theshadow27) [reply packages/command/src/commands/phase.ts]: Fixed in 7b4b1130 — same per-signal wrapper pattern as alias-runner.ts. See reply on that thread for details.

File: packages/command/src/commands/phase.ts [hunk 5]
```diff
@@ -1119,6 +1133,16 @@ export async function executePhase(
...
     : createEphemeralState();
+  const phaseController = new AbortController();
+  const onPhaseSignal = (sig: string) => {
+    phaseController.abort();
+    process.off("SIGINT", onPhaseSignal);
+    process.off("SIGTERM", onPhaseSignal);
+    process.kill(process.pid, sig);
+  };
+  process.once("SIGINT", onPhaseSignal);
+  process.once("SIGTERM", onPhaseSignal);
```
[the remark this answers is not in the document]
Comment (theshadow27) [reply packages/command/src/commands/phase.ts]: Fixed in 7b4b1130 — same per-signal wrapper pattern. Uses `onPhaseInt`/`onPhaseTerm` to avoid shadowing the `onInt`/`onTerm` from `runPhase` above.

File: packages/daemon/src/alias-executor.ts [hunk 6]
```diff
@@ -139,6 +139,18 @@ async function main(): Promise<void> {
...
 
+  // Wire cancellation: SIGINT from the terminal or SIGTERM from the daemon
+  // killing this subprocess both abort waitForEvent calls.
+  const controller = new AbortController();
+  const onSignal = (sig: string) => {
+    controller.abort();
+    process.off("SIGINT", onSignal);
+    process.off("SIGTERM", onSignal);
+    process.kill(process.pid, sig);
+  };
```
[the remark this answers is not in the document]
Comment (theshadow27) [reply packages/daemon/src/alias-executor.ts]: Fixed in 7b4b1130 — same per-signal wrapper pattern as the other 3 callsites.

File: packages/core/src/event-filter.ts [hunk 7]
```diff
@@ -107,23 +107,26 @@ type OpenStreamFn = typeof openEventStream;
...
  */
-export function createWaitForEvent(
-  openStream: OpenStreamFn = openEventStream,
-): (filter: EventFilterSpec, opts?: { timeoutMs?: number; since?: number }) => Promise<MonitorEvent> {
+export function createWaitForEvent(opts?: {
+  openStream?: OpenStreamFn;
+  signal?: AbortSignal;
+}): (filter: EventFilterSpec, opts?: { timeoutMs?: number; since?: number }) => Promise<MonitorEvent> {
+  const { openStream = openEventStream, signal } = opts ?? {};
+
```
[the remark this answers is not in the document]
Comment (theshadow27) [reply packages/core/src/event-filter.ts:129]: Fixed in 7b4b1130 — updated PR description to document the actual `{ openStream?, signal? }` opts-object signature.

File: packages/core/src/alias.ts [hunk 8]
```diff
@@ -147,16 +147,23 @@ export interface AliasContext {
...
    */
   workItem: AliasWorkItemInfo | null;
+  /**
+   * Cancellation signal for this alias invocation. Fires on SIGINT, SIGTERM,
+   * or daemon shutdown. Aliases that do long-running work should check this
+   * signal and abort gracefully. `waitForEvent` is wired to this signal
+   * automatically — a fired signal causes an in-progress wait to reject
+   * immediately with `signal.reason` (an AbortError by default).
+   */
+  signal: AbortSignal;
```
[the remark this answers is not in the document]
Comment (theshadow27) [reply packages/core/src/alias.ts:157]: Fixed in 7b4b1130 — updated PR description to say `signal: AbortSignal` (required). Making it required is intentional: every alias invocation now gets a controller, so there's always a signal available.

**Comment by theshadow27** [comment]
## Repair round 4 — 7b4b1130

### sig=undefined bug (4 callsites)
`process.once("SIGINT"/"SIGTERM")` handlers receive **no arguments**, so the shared `onSignal(sig: string)` handler got `undefined` and `process.kill(pid, undefined)` defaulted to SIGTERM regardless of which signal actually fired.

**Fix:** Split into per-signal wrapper closures (`onInt`/`onTerm`) that capture the signal name explicitly, then delegate to a shared `onSignal(sig: NodeJS.Signals)`. Applied to all 4 callsites:
- `packages/command/src/alias-runner.ts`
- `packages/daemon/src/alias-executor.ts`
- `packages/command/src/commands/phase.ts` (runPhase)
- `packages/command/src/commands/phase.ts` (executePhase)

### PR description (2 nits)
- Updated `createWaitForEvent` signature docs: `{ openStream?, signal? }` opts object (not polymorphic first-arg)
- Updated `AliasContext.signal` docs: required, not optional

### CI
- `check` job: typecheck passes locally with `--force`; prior CI failure was likely stale `.tsbuildinfo`
- `coverage` job: Bun crash (known upstream, #1004) — CI retry logic should handle it
- All 33 event-filter tests pass, full typecheck + lint clean

**Comment by theshadow27** [comment]
## QA Verification

**PR:** #1758 — feat(alias): wire AbortSignal cancellation into waitForEvent (fixes #1714)
**Linked issue:** #1714

### Implementation Evidence
- `packages/core/src/alias.ts:157` — `AliasContext.signal: AbortSignal` added (required, not optional)
- `packages/core/src/event-filter.ts:124-203` — `createWaitForEvent` changed from `(openStream: OpenStreamFn)` to `(opts?: { openStream?, signal? })`. Pre-aborted signal → immediate rejection (line 166-169); in-flight abort → `onAbort` listener (line 140-142); listener removed in `cleanup()` on all resolution paths (line 144-151)
- `packages/command/src/alias-runner.ts:31-91` — `AbortController` per invocation, per-signal wrappers `onInt`/`onTerm`, listeners removed in `finally`, signal wired to `createWaitForEvent`
- `packages/daemon/src/alias-executor.ts:144-182` — same pattern; `phaseController` + per-signal wrappers
- `packages/command/src/commands/phase.ts:824-861` (`runPhase`) and `1138-1188` (`executePhase`) — both dry-run and real-execution paths wire `AbortController` + SIGINT/SIGTERM cleanup

### Test Coverage
- `packages/core/src/event-filter.spec.ts` — 33 tests covering:
  - pre-aborted signal → immediate `AbortError` rejection (line 251-257)
  - signal fires while waiting → `AbortError` rejection (line 259-280)
  - abort listener removed on normal resolution — no leaked listeners (line 282-299)
  - abort listener removed on timeout — no leaked listeners (line 301-331)
  - signal aborted between listener registration and check — no missed abort (race condition test, line 333-357)
  - abort after resolve / abort after timeout — settled flag prevents double-rejection (lines 359-389)

### Test Results
All 33 tests in `event-filter.spec.ts` pass locally on the PR branch. Local `bun typecheck` also passes (exit 0).

### CI Status
**FAILING** — `check` job: typecheck fails at merge time.

**Root cause:** Main's commit `228fe5d3` (merged to main after this branch was cut, via PR #1760) added a new test to `event-filter.spec.ts`:
```
test("empty-spec waitForEvent({}) skips normalized heartbeats...", async () => {
    const waitFor = createWaitForEvent(() => fakeStream([hb, target]));  // ← OLD API
```
When CI creates the merge commit (PR branch + current main), this test uses the OLD `createWaitForEvent(openStream)` signature but `event-filter.ts` now expects the NEW `createWaitForEvent({ openStream?, signal? })` form. Result:
```
event-filter.spec.ts(230,40): error TS2559: Type '() => { events: AsyncIterable<MonitorEvent>; abort: () => void; }' has no properties in common with type '{ openStream?: ... | undefined; signal?: AbortSignal | undefined; }'
```

### Remaining Work (non-blocking)
None beyond the fix below.

### Outcome
**qa:fail** — CI typecheck fails due to merge conflict with main's `228fe5d3`. The PR branch spec does not include (and update) the new test added by #1760.

**Action for implementation:** Rebase/merge with current main, then update the new test from #1760 to use the new API:
```typescript
// Change this (old API):
const waitFor = createWaitForEvent(() => fakeStream([hb, target]));
// To this (new API):
const waitFor = createWaitForEvent({ openStream: () => fakeStream([hb, target]) });
```
One-line fix in `packages/core/src/event-filter.spec.ts`.

**Comment by theshadow27** [comment]
Rebased onto main (picks up #1760/228fe5d3). Fixed the one new test that used the old `createWaitForEvent(fn)` single-arg form:

```diff
-    const waitFor = createWaitForEvent(() => fakeStream([hb, target]));
+    const waitFor = createWaitForEvent({ openStream: () => fakeStream([hb, target]) });
```

All 34 `event-filter.spec.ts` tests pass, typecheck clean.

**Comment by theshadow27** [comment]
## QA Verification

**PR:** #1758 — feat(alias): wire AbortSignal cancellation into waitForEvent (fixes #1714)
**Linked issue:** #1714

### Implementation Evidence
- `packages/core/src/alias.ts:157` — `AliasContext.signal: AbortSignal` added as required field, documented with correct semantics (fires on SIGINT/SIGTERM/daemon shutdown, wired to `waitForEvent` automatically)
- `packages/core/src/event-filter.ts:120-203` — `createWaitForEvent` signature changed from `(openStream)` to `({ openStream?, signal? })`. Abort listener registered **before** the pre-aborted check (closes TOCTOU race). `onAbort`/`cleanup`/`settle` pattern ensures listener removal on every resolution path (resolve, timeout, abort, stream-end)
- `packages/command/src/alias-runner.ts:31-91` — `AbortController` per invocation; per-signal wrappers `onInt`/`onTerm` capture signal name explicitly (avoiding the `undefined` arg bug); re-raises signal after abort; listeners removed in `finally`
- `packages/daemon/src/alias-executor.ts:144-182` — identical pattern for daemon subprocess path
- `packages/command/src/commands/phase.ts:824-861` (`runPhase`) and `1138-1188` (`executePhase`) — both dry-run and real-execution paths fully wired

### Test Coverage
- `packages/core/src/event-filter.spec.ts` — 8 AbortSignal-specific tests:
  - Pre-aborted signal → immediate `AbortError` rejection
  - Signal fires while waiting → `AbortError` rejection
  - Abort listener removed on normal resolution (no leaked listeners)
  - Abort listener removed on timeout (no leaked listeners)
  - TOCTOU race: signal aborted between `addEventListener` and `aborted` check — no missed abort
  - Abort after resolve — `settled` flag prevents double-rejection (idempotency)
  - Abort after timeout — `settled` flag prevents double-rejection (idempotency)
- `packages/core/src/alias-bundle.spec.ts` — 7 `AliasContext` stubs updated with `signal: new AbortController().signal`
- `packages/core/src/alias-dry-run.spec.ts` — 2 `AliasContext` stubs updated

### Test Results
Full suite green in CI: 5921 pass, 0 fail (check job, 4m0s). Coverage thresholds met (coverage job, 5m58s).

### CI Status
✅ **All passing** — run [24912321048](https://github.com/theshadow27/mcp-cli/actions/runs/24912321048)
- `check` ✓ (4m0s): typecheck, lint, phase drift guard, non-daemon tests, daemon tests
- `coverage` ✓ (5m58s): coverage thresholds met
- `build` ✓ (9s): binaries compile and pass smoke test

### Step 5b Gate — Copilot Threads
All 8 Copilot inline threads have owner replies (`has_owner_reply: true`). 0 unreplied threads. Gate: **CLEAR**.
No `CHANGES_REQUESTED` reviews outstanding.

### Remaining Work (non-blocking)
None flagged in the issue.

### Outcome
**qa:pass** — All described functionality implemented and verified. Tests (8 new AbortSignal-specific, all 5921 suite) and CI fully green. All Copilot threads replied to.
