### ISSUE TITLE
.claude/phases/*-fn.spec.ts ignored by CI; test/*-phase.spec.ts mirrors drift silently

### ISSUE THREAD

**Issue by theshadow27** [theshadow27/mcp-cli#2648]
## Problem

`bunfig.toml` sets `pathIgnorePatterns = [".claude/**", ...]`, so `bun test` (and therefore `am-i-done --ci`, which is what CI runs) never discovers the co-located phase specs in `.claude/phases/*-fn.spec.ts`.

CI coverage of phase logic comes **only** from hand-maintained mirror files under `test/*-phase.spec.ts`. The `test:phases` script (`cd .claude/phases && bun test`) exists in `package.json` but is **not wired into any CI job** — `grep -rn "test:phases" .github/workflows/` returns no hits.

## Impact

1. Every phase module requires two near-identical spec files that drift silently — nothing enforces parity between `.claude/phases/<name>-fn.spec.ts` and `test/<name>-phase.spec.ts`.
2. If an author edits only the co-located spec (the natural place, next to the source), CI runs the stale `test/` copy and the change is untested in CI.
3. Concrete near-miss (#2575 fix): deleted `test/review-phase.spec.ts` assuming it was a pure duplicate of `.claude/phases/review-fn.spec.ts` — that would have removed the **only CI-enforced coverage** for `review-fn.ts`. Had to restore it.

## Repro

```bash
# Confirm .claude/** is excluded
grep pathIgnorePatterns bunfig.toml

# Confirm test:phases is not in CI
grep -rn "test:phases" .github/workflows/   # no output

# Confirm both files exist for the same module
ls .claude/phases/review-fn.spec.ts test/review-phase.spec.ts
```

## Suggested fixes (pick one)

**(a)** Wire `test:phases` (or an equivalent `bun test .claude/phases`) into `am-i-done --ci` and/or the CI `check` job so co-located specs become the single source of truth and `test/*-phase.spec.ts` mirrors can be deleted.

**(b)** Document the convention explicitly: `test/*-phase.spec.ts` is canonical; remove `.claude/phases/*-fn.spec.ts` so there is one file, one location, no drift risk.

**(c)** Add an architectural rule (`doing-it-wrong`) that fails if a `.claude/phases/*-fn.ts` exists without a corresponding `test/*-phase.spec.ts`, making the mirror requirement machine-enforced.

## Prior art

Same root cause (`pathIgnorePatterns` silencing specs) was filed for `scripts/**` exclusion in #1484 (closed) and #1936 (closed). Those were fixed for `scripts/`; `.claude/**` was not addressed.

**Comment by theshadow27** [comment]
New concrete instance confirming the gap: PR #2671 added `phase-types.spec.ts` under `.claude/phases/` as part of the fix for #2653 (prEdit --add-label). This spec validates the `PhaseOp` type contract and the `--add-label` parsing behavior — but because `.claude/**` is excluded by `pathIgnorePatterns`, the test runs only if someone manually `cd .claude/phases && bun test` from their local machine.

Additionally, `done-fn.spec.ts` has at least one pre-existing failure that CI never catches for the same reason.

The pattern is now repeating: every phase fix naturally produces a co-located spec that CI silently ignores. Fix (a) from the original report (wire `test:phases` into `am-i-done`) is the lowest-friction path.

**Comment by theshadow27** [comment]
New concrete evidence from #2692 (fixed in PR ffd2309c):

`done-fn.spec.ts` had 7 failing tests that went undetected since PR #2192 merged. The stubs in the spec still used the old positional `args[]` interface; the implementation had moved to a typed `GhOp` interface. Because `.claude/**` is excluded from `am-i-done` and CI, the breakage was invisible for the entire intervening period.

Symptom:
```
TypeError: ctx.mcp.call is not a function
  at done-fn.spec.ts (multiple tests)
```

Fix was updating the stubs in `.claude/phases/done-fn.spec.ts` to match the `GhOp` interface. The `test:phases` script (`cd .claude/phases && bun test`) would have caught this immediately.

This is option **(a)** from the suggested fixes above: wiring `test:phases` into `bun run am-i-done` (and therefore CI) is the lowest-friction path. The `package.json` script already exists — it just needs a line in `scripts/am-i-done.ts` to invoke it.

Relevant files:
- `scripts/am-i-done.ts` — runner to modify
- `.claude/phases/done-fn.spec.ts` — the spec that drifted
- `package.json` — `test:phases` script exists, not wired

**Comment by theshadow27** [comment]
New evidence from issue #2683 investigation (commit f4c4a5e1, 2026-06-11):

**The exact 7 failures that the missing gate hides are now confirmed on clean main:**

```
bun run test:phases   # cd .claude/phases && bun test --no-orphans
```

All 7 failures in `.claude/phases/done-fn.spec.ts`, `mergePr` describe block:

```
(fail) mergePr > succeeds when labels include qa:pass and CI is green
(fail) mergePr > returns ci_not_green when failing checks > 0
(fail) mergePr > recovers from interrupted merge when prView returns MERGED
(fail) mergePr > returns merge_failed when interrupted merge prView returns non-MERGED
(fail) mergePr > returns conflicts when merge stderr mentions conflicts
(fail) mergePr > returns ok:true when concurrent rerun sees 'not mergeable' but PR is already MERGED
(fail) mergePr > falls back to conflicts classification when prView fails and stderr matches
```

Every affected test receives `"missing_qa_pass"` instead of the expected result — identical symptom to #2571 (closed 2026-06-11). #2571 was closed but the failures are live again on main; this is a regression of that issue.

**Confirmed wiring gaps (grep returns zero hits on commit f4c4a5e1):**
- `grep -rn "test:phases" .github/workflows/` — 0 matches
- `grep -rn "test:phases" .git-hooks/` — 0 matches
- `grep -rn "test:phases" scripts/am-i-done.ts` — 0 matches
- `scripts/am-i-done.ts` line 234 step list: `[INSTALL, TYPECHECK, LINT, RULES, AGENT_GRID, TEST_PARALLEL, TEST_CONTROL, COVERAGE]` — no phases step

These failures would have been caught if `test:phases` were in the gate. Both the wiring fix (this issue) and the test fixture repair (regression of #2571) are needed together.
