### PR TITLE
fix(phases): Array.isArray guard + typeof roundStartedAt check in review-fn/qa-fn (closes #2686, closes #2687)

### LINKED ISSUE #2686: Missing Array.isArray guard in readReviewLabels / readQaLabels causes cryptic TypeError on non-array JSON
## Problem

In `readReviewLabels` (`.claude/phases/review-fn.ts:74-79`) and `readQaLabels` (`.claude/phases/qa-fn.ts:67-72`), `JSON.parse` is called on `gh api` output and the result is immediately used as an array:

```typescript
let events: GhLabelEvent[];
try {
  events = JSON.parse(eventsResult.stdout);
} catch {
  return fail-closed;
}
// no Array.isArray check here
events.filter(...) // throws TypeError if events is {} or "hello"
```

If GitHub returns valid JSON that is not an array (e.g., an error object `{}`, a string, or a wrapped response), `JSON.parse` succeeds but `events.filter(...)` throws:

```
TypeError: events.filter is not a function
```

The phase script crashes. The fail-closed behavior is accidental (unhandled TypeError), not intentional.

## Impact

- P3 — only triggerable via a GitHub API regression or MITM returning unexpected JSON shape
- The phase script crash is noisier than a clean rejection return
- Error message `"events.filter is not a function"` has zero diagnostic value — no indication of what was actually returned
- Fail-closed by accident, not by design; the intent of the surrounding `try/catch` is clearly to detect bad JSON, not non-array JSON

## Repro

Send a response from `gh api .../events` that returns `{}` or `{"message":"Not Found"}` (valid JSON, not an array). The phase script crashes with a TypeError rather than returning the clean fail-closed sentinel.

## Fix

Add an explicit `Array.isArray` guard immediately after `JSON.parse` in both functions:

```typescript
events = JSON.parse(eventsResult.stdout);
if (!Array.isArray(events)) {
  return { hasPass: false, hasChanges: false, rejections: ["label-events response is not an array — fail closed"] };
}
```

**Files:**
- `.claude/phases/review-fn.ts:74-79`
- `.claude/phases/qa-fn.ts:67-72`

Related: PR #2678 (verdict label validation)

### LINKED ISSUE #2687: type-safety gap in verdict freshness guard: roundStartedAt typeof check missing (review-fn.ts:162, qa-fn.ts:138)
## Problem

In `.claude/phases/review-fn.ts:162` and `.claude/phases/qa-fn.ts:138`, `roundStartedAt` is read from SQLite state with:

```ts
const roundStartedAt = (await state.get<number>("review_spawned_at")) ?? 0;
```

The guards that follow check:

```ts
if (roundStartedAt === 0 || Number.isNaN(roundStartedAt)) { /* skip freshness */ }
```

If the SQLite layer ever returns this value as a string (e.g., `"1718000000000"` instead of `1718000000000`), **both guards pass silently**:

- `"0" === 0` — false (strict equality, different types)
- `Number.isNaN("0")` — false (`Number.isNaN` does not coerce)
- In `validateVerdictLabel`, `eventTime < "1718000000000"` then uses JS string coercion — which happens to work for non-zero values, but `"0"` would bypass the freshness guard entirely

The TypeScript generic `<number>` has zero runtime enforcement — it is a cast, not a validation.

## Impact

**P2 — latent fail-open.** Under normal operation `state.set` always writes `Date.now()` (a number), so the bug requires a SQLite type-affinity round-trip issue to trigger. However, if that ever occurs, `validateVerdictLabel` would skip the freshness check and allow a stale verdict label to be accepted without warning. Introduced in PR #2678.

## Repro

Reproducible only by injecting a string into the SQLite state store for `review_spawned_at` / `qa_spawned_at` and then running a verdict-label validation pass. Not currently triggerable in production.

## Suggested Fix

Add a `typeof` check alongside the existing guards in both files:

```ts
// review-fn.ts:163 / qa-fn.ts:139
if (
  typeof roundStartedAt !== "number" ||
  roundStartedAt === 0 ||
  Number.isNaN(roundStartedAt)
) {
  // skip freshness validation — no reliable anchor
}
```

Alternatively, force coercion with a NaN guard:

```ts
const roundStartedAt = Number(
  (await state.get<number>("review_spawned_at")) ?? 0
);
```

## Files

- `.claude/phases/review-fn.ts:162-164`
- `.claude/phases/qa-fn.ts:138-140`

### PR DESCRIPTION
**Pull request by theshadow27**
## Summary

- **`readReviewLabels` / `readQaLabels`** (#2686): added `Array.isArray` guard immediately after `JSON.parse` in both `review-fn.ts` and `qa-fn.ts`; a non-array GitHub API response (e.g. `{"message":"Not Found"}`) now returns a clean fail-closed sentinel with a diagnostic rejection message instead of throwing `TypeError: events.filter is not a function`
- **`runReview` / `runQa` freshness guards** (#2687): added `typeof roundStartedAt !== "number"` as the first condition in the `review_spawned_at` / `qa_spawned_at` guards; a SQLite type-affinity string round-trip can no longer silently pass strict-equality and `Number.isNaN` checks, bypassing freshness validation
- Supersedes PR #2700 (same Array.isArray fix, but without the typeof check and without dropping the `.claude/commands/qa.md` hunk already merged in #2701)

## Test plan

- [ ] `fail closed: non-array label events rejects all verdicts (#2686)` added to `review-fn.spec.ts` and `qa-fn.spec.ts`
- [ ] `returns wait when review_spawned_at/qa_spawned_at is a string (typeof guard #2687)` added to both spec files
- [ ] `bun run am-i-done` passes (typecheck → lint → rules → tests → coverage)

Closes #2686
Closes #2687

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by theshadow27** [comment]
## QA Verification

**PR:** #2711 — fix(phases): Array.isArray guard + typeof roundStartedAt check in review-fn/qa-fn (closes #2686, closes #2687)
**Linked issues:** #2686, #2687

### Implementation Evidence

- **`readReviewLabels` (#2686)** — `review-fn.ts:80-82`: `Array.isArray` guard immediately after `JSON.parse`; returns `{ hasPass: false, hasChanges: false, rejections: ["label-events not an array — fail closed"] }` on non-array JSON
- **`readQaLabels` (#2686)** — `qa-fn.ts:73-75`: identical guard; fail-closed with diagnostic rejection message
- **`runReview` freshness guard (#2687)** — `review-fn.ts:166`: `typeof roundStartedAt !== "number"` added as first condition; SQLite string round-trip now returns `action: "wait"` with `fail closed` reason
- **`runQa` freshness guard (#2687)** — `qa-fn.ts:142`: same typeof guard; same fail-closed path
- **Supersedes PR #2700** (closed without merge): Array.isArray fix from #2700 is fully incorporated; qa.md hunk was intentionally omitted — already merged in #2701

### Test Coverage

- `review-fn.spec.ts:176`: `"fail closed: non-array label events rejects all verdicts (#2686)"` — simulates `pr:label-events` returning `{"message":"Not Found"}`; asserts `hasPass=false` and rejection matches `/label-events not an array/`
- `review-fn.spec.ts:325`: `"returns wait when review_spawned_at is a string (typeof guard #2687)"` — injects `"1718000000000"` (string) into state; asserts `action=wait` with `/fail closed/`
- `qa-fn.spec.ts:138`: `"fail closed: non-array label events rejects all verdicts (#2686)"` — simulates `{"foo":1}` response; asserts `hasPass=false` and rejection matches `/label-events not an array/`
- `qa-fn.spec.ts:254`: `"returns wait when qa_spawned_at is a string (typeof guard #2687)"` — injects string; asserts `action=wait` with `/fail closed/`

### Test Results

`bun run test:phases` → **105 pass, 0 fail** across 6 files

### CI Status

All 5 checks green: `build`, `check`, `coverage`, `detect`, `pty-test` — run [27326376331](https://github.com/theshadow27/mcp-cli/actions/runs/27326376331)

### Typecheck

`bun typecheck` — clean (no errors)

### Remaining Work (non-blocking)

None identified.

### Outcome

**qa:pass** — Both #2686 (Array.isArray guard in `readReviewLabels`/`readQaLabels`) and #2687 (typeof check on `roundStartedAt` in `runReview`/`runQa`) are implemented and tested in both phase files. Tests are meaningful (simulate exact failure modes from each issue). Suite and CI are green.
