### PR TITLE
fix(types): add waitForEvent to AliasContext type stubs (fixes #2052)

### LINKED ISSUE #2052: docs/types: ambient mcp-cli.d.ts template and internal stubs missing waitForEvent on AliasContext
## Background

Discovered during QA of #2017 / PR #2045 (ambient \`.d.ts\` template for phase script type safety).

## Problem

\`AliasContext.waitForEvent\` exists in \`packages/core/src/alias.ts:180\`:

\`\`\`typescript
waitForEvent(filter: EventFilterSpec, opts?: { timeoutMs?: number; since?: number }): Promise<MonitorEvent>;
\`\`\`

But it is absent from all three type stubs:

1. **PR #2045 ambient template** (\`docs/phases.md\`) — the copy-paste \`.d.ts\` for phase script authors
2. **\`packages/core/src/alias-bundle.ts:MCP_CLI_STUB_DTS\`** (line ~474) — the internal stub used for tsc validation of freeform aliases
3. **\`packages/command/src/commands/typegen.ts\`** (line ~66-76) — the generated \`AliasContext\` output

Phase scripts that call \`ctx.waitForEvent(...)\` will see \`TS2339: Property 'waitForEvent' does not exist on type 'AliasContext'\` with any of these stubs.

## Proposed Fix

Add \`waitForEvent\` to all three stubs. The signature requires \`EventFilterSpec\` and \`MonitorEvent\` — either import them or inline a minimal structural version in the stub.

## Relevant Files

- \`packages/core/src/alias.ts:180\` — authoritative definition
- \`packages/core/src/alias-bundle.ts:474-504\` — MCP_CLI_STUB_DTS
- \`packages/command/src/commands/typegen.ts:66-76\` — generateMcpCliDts AliasContext block
- \`docs/phases.md\` — ambient d.ts template (Option A section)

### PR DESCRIPTION
**Pull request by theshadow27**
## Summary

- Adds `waitForEvent`, `EventFilterSpec`, and `MonitorEvent` to the two internal `AliasContext` type stubs so phase scripts calling `ctx.waitForEvent(...)` no longer see `TS2339: Property 'waitForEvent' does not exist on type 'AliasContext'`.
- `packages/core/src/alias-bundle.ts` `MCP_CLI_STUB_DTS`: adds full `AliasContext` interface (the stub previously only exposed top-level exports for freeform aliases) plus the two new structural types and `waitForEvent`.
- `packages/command/src/commands/typegen.ts` `generateDeclarations`: adds `EventFilterSpec`, `MonitorEvent` interfaces and `waitForEvent` to the generated `AliasContext` block.

Authoritative definition lives in `packages/core/src/alias.ts:180`; structural inline copies are used in the stubs (which can't `import` from real modules).

`docs/phases.md` ambient template is intentionally not in this PR per scope guidance.

## Test plan

- [x] `bun typecheck` — passes
- [x] `bun lint` — passes
- [x] `bun test packages/command/src/commands/typegen.spec.ts` — 15/15 pass, including new `AliasContext includes waitForEvent` assertion
- [x] `bun test packages/core/src/alias-bundle-tsc.spec.ts` — 5/5 pass in isolation, including new `AliasContext.waitForEvent resolves without type error` tsc-validation test
- [x] Full pre-commit hook (typecheck + lint + doing-it-wrong + args-bounds + timeouts + teardown + phase-drift + test + coverage) — green

## Notes

- Filed #2083 for pre-existing `alias-bundle-tsc.spec.ts` parallel-suite flake (pre-commit fast path skips it so this PR isn't affected).

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by theshadow27** [comment]
## QA Verification

**PR:** #2085 — fix(types): add waitForEvent to AliasContext type stubs (fixes #2052)
**Linked issue:** #2052

### Implementation Evidence

- `packages/core/src/alias-bundle.ts:490-520` — Added `EventFilterSpec`, `MonitorEvent` interfaces and full `AliasContext` interface (with `waitForEvent`) to `MCP_CLI_STUB_DTS`. Previously the stub only exposed top-level freeform exports without the `AliasContext` interface at all.
- `packages/command/src/commands/typegen.ts:68-96` — Added `EventFilterSpec`, `MonitorEvent` interfaces and `waitForEvent` to the `generateDeclarations` output's `AliasContext` block.
- Both implementations use inline structural copies of the types (not imports), consistent with how stubs work.

### Test Coverage

- `packages/command/src/commands/typegen.spec.ts:120-122` — "AliasContext includes waitForEvent" assertion confirms generated DTS contains the correct signature.
- `packages/core/src/alias-bundle-tsc.spec.ts:53-73` — "AliasContext.waitForEvent resolves without type error" runs a tsc validation that calls `ctx.waitForEvent(...)` and asserts no type errors.
- 20/20 tests pass across both files.

### Test Results

7247 pass, 0 fail across 302 files (full suite).

### CI Status

All checks pass:
- `check` ✅ (2m24s)
- `coverage` ✅ (2m6s)
- `build` ✅ (8s)
- `pty-test` ✅ (19s)

### Remaining Work (non-blocking)

- `docs/phases.md` ambient template still missing `waitForEvent` — intentionally excluded from this PR's scope. Filed #2088 to track.
- Pre-existing `alias-bundle-tsc.spec.ts` parallel-suite flake filed as #2083 (noted in PR body).

### Outcome

**qa:pass** — Both targeted stubs (`alias-bundle.ts` and `typegen.ts`) correctly implement `waitForEvent` with supporting types. Tests are meaningful (tsc validation included), full suite green, CI green.

File: packages/core/src/alias-bundle-tsc.spec.ts [hunk 1]
```diff
@@ -50,6 +50,30 @@ describe("validateFreeformTsc", () => {
...
+        "  },",
+        "});",
+      ].join("\n"),
+    );
+
+    const result = await validateFreeformTsc(scriptPath);
+
+    expect(result.timedOut).toBe(false);
+    const waitErrors = result.warnings.filter((w) => w.includes("waitForEvent"));
+    expect(waitErrors).toHaveLength(0);
```
[the remark this answers is not in the document]
Comment (theshadow27) [reply packages/core/src/alias-bundle-tsc.spec.ts]: Fixed: changed the assertion to `expect(result.warnings).toHaveLength(0)` so the test proves the stub compiles with zero diagnostics, not just zero waitForEvent-filtered warnings. Committed in cd05cb3.

File: packages/core/src/alias-bundle.ts [hunk 2]
```diff
@@ -487,6 +487,38 @@ declare module "mcp-cli" {
...
+    mcp: Record<string, Record<string, (args?: Record<string, unknown>) => Promise<unknown>>>;
+    args: Record<string, string>;
+    file: (path: string) => Promise<string>;
+    json: (path: string) => Promise<unknown>;
+    state: { get<T = unknown>(key: string): Promise<T | undefined>; set(key: string, value: unknown): Promise<void>; delete(key: string): Promise<void>; all(): Promise<Record<string, unknown>> };
+    globalState: { get<T = unknown>(key: string): Promise<T | undefined>; set(key: string, value: unknown): Promise<void>; delete(key: string): Promise<void>; all(): Promise<Record<string, unknown>> };
+    workItem: { id: string; issueNumber: number | null; prNumber: number | null; branch: string | null; phase: string } | null;
+    repoRoot: string;
+    signal: AbortSignal;
+    waitForEvent(filter: EventFilterSpec, opts?: { timeoutMs?: number; since?: number }): Promise<MonitorEvent>;
```
[the remark this answers is not in the document]
Comment (theshadow27) [reply packages/core/src/alias-bundle.ts:520]: PR #2085 scope was specifically waitForEvent (#2052); broader stub-completeness (cache, repoRoot, signal, MonitorCategory) tracked in #2089.

File: packages/command/src/commands/typegen.ts [hunk 3]
```diff
@@ -73,6 +93,7 @@ export function generateDeclarations(tools: ToolInfo[]): string {
     "    state: AliasStateAccessor;",
     "    globalState: AliasStateAccessor;",
     "    workItem: AliasWorkItemInfo | null;",
+    "    waitForEvent(filter: EventFilterSpec, opts?: { timeoutMs?: number; since?: number }): Promise<MonitorEvent>;",
     "  }",
```
[the remark this answers is not in the document]
Comment (theshadow27) [reply packages/command/src/commands/typegen.ts:97]: PR #2085 scope was specifically waitForEvent (#2052); broader stub-completeness (cache, repoRoot, signal, MonitorCategory) tracked in #2089.

File: packages/core/src/alias-bundle.ts [hunk 4]
```diff
@@ -487,6 +487,38 @@ declare module "mcp-cli" {
...
+    src?: string;
+    phase?: string;
+  }
+  export interface MonitorEvent {
+    seq: number;
+    ts: string;
+    src: string;
+    event: string;
+    category: string;
+    workItemId?: string;
```
[the remark this answers is not in the document]
Comment (theshadow27) [reply packages/core/src/alias-bundle.ts:505]: PR #2085 scope was specifically waitForEvent (#2052); broader stub-completeness (cache, repoRoot, signal, MonitorCategory) tracked in #2089.

File: packages/command/src/commands/typegen.ts [hunk 5]
```diff
@@ -65,6 +65,26 @@ export function generateDeclarations(tools: ToolInfo[]): string {
...
+    "  interface MonitorEvent {",
+    "    seq: number;",
+    "    ts: string;",
+    "    src: string;",
+    "    event: string;",
+    "    category: string;",
+    "    workItemId?: string;",
+    "    sessionId?: string;",
+    "    prNumber?: number;",
+    "    [key: string]: unknown;",
```
[the remark this answers is not in the document]
Comment (theshadow27) [reply packages/command/src/commands/typegen.ts:86]: PR #2085 scope was specifically waitForEvent (#2052); broader stub-completeness (cache, repoRoot, signal, MonitorCategory) tracked in #2089.

**Comment by theshadow27** [comment]
## QA Verification (updated)

**PR:** #2085 — fix(types): add waitForEvent to AliasContext type stubs (fixes #2052)
**Linked issue:** #2052

### Changes since initial qa:pass

- Copilot thread #3263622827 (test only filtered on \"waitForEvent\" keyword, could miss other diagnostics) — **fixed** in commit cd05cb3: assertion changed to `expect(result.warnings).toHaveLength(0)`.
- Threads #3263622746, #3263622774, #3263622792, #3263622804 (stub missing cache/repoRoot/signal; EventFilterSpec.subscribe too loose) — out of scope for #2052; tracked in #2089.
- All 5 Copilot threads replied. Zero unreplied threads remaining.

### Implementation Evidence

- `packages/core/src/alias-bundle.ts:490-521` — `EventFilterSpec`, `MonitorEvent`, full `AliasContext` with `waitForEvent` added to `MCP_CLI_STUB_DTS`
- `packages/command/src/commands/typegen.ts:68-96` — same types added to `generateDeclarations` output

### Test Coverage

- `packages/core/src/alias-bundle-tsc.spec.ts:53-74` — asserts `result.warnings.toHaveLength(0)` (no diagnostics at all for a script using `ctx.waitForEvent`)
- `packages/command/src/commands/typegen.spec.ts:120-122` — asserts generated DTS contains the correct signature

### Test Results

7247 pass, 0 fail (full suite, run locally on branch).

### CI Status

All checks pass: `check` ✅ `coverage` ✅ `build` ✅ `pty-test` ✅

### Remaining Work (non-blocking)

- #2088 — `docs/phases.md` ambient template still missing `waitForEvent` (intentionally out of scope)
- #2089 — AliasContext stubs missing `cache`/`repoRoot`/`signal`; `EventFilterSpec.subscribe` should use `MonitorCategory[]`

### Outcome

**qa:pass** — Fix implemented, test tightened to assert zero diagnostics, all Copilot threads resolved, CI green.
